# Generated by Django 4.1.7 on 2023-02-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, to='chats.user'),
        ),
    ]
